#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$PROJECT_ROOT/.env.local"
SEED_FILE="$PROJECT_ROOT/supabase/seed.sql"

command -v supabase >/dev/null 2>&1 || {
  echo "Error: Supabase CLI is not installed. Install it from https://supabase.com/docs/guides/cli" >&2
  exit 1
}

if ! command -v docker >/dev/null 2>&1; then
  echo "Error: Docker is required to run the Supabase local stack." >&2
  exit 1
fi

pushd "$PROJECT_ROOT" >/dev/null

if [ ! -f "$ENV_FILE" ]; then
  if [ -f "$PROJECT_ROOT/.env.example" ]; then
    cp "$PROJECT_ROOT/.env.example" "$ENV_FILE"
  else
    touch "$ENV_FILE"
  fi
fi

echo "▶️ Starting Supabase local stack..."
supabase start

echo "♻️ Resetting database and applying migrations..."
if [ -f "$SEED_FILE" ]; then
  supabase db reset --force --seed "$SEED_FILE"
else
  supabase db reset --force
fi

BRANCH_ENV=""
if [ -d "$PROJECT_ROOT/supabase/.branches" ]; then
  BRANCH_ENV=$(find "$PROJECT_ROOT/supabase/.branches" -maxdepth 2 -name .env -print 2>/dev/null | head -n 1 || true)
fi

if [ -n "${BRANCH_ENV:-}" ] && [ -f "$BRANCH_ENV" ]; then
  echo "📦 Syncing environment variables from $(dirname "$BRANCH_ENV")/.env"
  SUPABASE_URL=$(grep -E '^SUPABASE_URL=' "$BRANCH_ENV" | tail -n 1 | cut -d '=' -f2- || true)
  ANON_KEY=$(grep -E '^(SUPABASE_)?ANON_KEY=' "$BRANCH_ENV" | tail -n 1 | cut -d '=' -f2- || true)
  SERVICE_ROLE_KEY=$(grep -E '^(SUPABASE_)?SERVICE_ROLE_KEY=' "$BRANCH_ENV" | tail -n 1 | cut -d '=' -f2- || true)
  JWT_SECRET=$(grep -E '^(SUPABASE_)?JWT_SECRET=' "$BRANCH_ENV" | tail -n 1 | cut -d '=' -f2- || true)

  {
    echo "# Generated by supabase/setup.sh"
    echo "NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL:-http://127.0.0.1:54321}"
    echo "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_OR_ANON_KEY=${ANON_KEY:-anon-key-placeholder}"
    [ -n "${SERVICE_ROLE_KEY:-}" ] && echo "SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}"
    [ -n "${JWT_SECRET:-}" ] && echo "SUPABASE_JWT_SECRET=${JWT_SECRET}"
  } > "$ENV_FILE"
  echo "✍️ Wrote local Supabase credentials to $(basename "$ENV_FILE")"
else
  cat <<EOM
⚠️ Could not locate a Supabase branch .env file. Please update $ENV_FILE with your Supabase credentials.
Required variables:
  NEXT_PUBLIC_SUPABASE_URL
  NEXT_PUBLIC_SUPABASE_PUBLISHABLE_OR_ANON_KEY
Optional server-side:
  SUPABASE_SERVICE_ROLE_KEY
  SUPABASE_JWT_SECRET
EOM
fi

echo "✅ Supabase local environment is ready. Launch the Next.js app with 'npm run dev'."

popd >/dev/null
