import type { CommandProvider } from "@/core/command/types"

export const systemCommands: CommandProvider = (ctx) => [
  {
    id: "system.dashboard",
    title: "Go to Dashboard",
    subtitle: "Return to main dashboard",
    section: "Navigation",
    icon: "home",
    shortcut: "⌘D",
    keywords: ["dashboard", "home", "main"],
    action: { kind: "navigate", href: "/dashboard" },
  },
  {
    id: "system.profile",
    title: "User Profile",
    subtitle: "View and edit your profile",
    section: "Account",
    icon: "user",
    keywords: ["profile", "account", "settings"],
    action: { kind: "navigate", href: "/profile" },
  },
  {
    id: "system.settings",
    title: "System Settings",
    subtitle: "Configure application settings",
    section: "Administration",
    icon: "settings",
    keywords: ["settings", "config", "admin"],
    when: (c) => c.user.roles.includes("admin"),
    action: { kind: "navigate", href: "/settings" },
  },
  {
    id: "system.users",
    title: "Manage Users",
    subtitle: "User administration",
    section: "Administration",
    icon: "users",
    keywords: ["users", "admin", "manage"],
    when: (c) => c.user.roles.includes("admin"),
    action: { kind: "navigate", href: "/admin/users" },
  },
  {
    id: "system.reports",
    title: "Generate Reports",
    subtitle: "Create system reports",
    section: "Reports",
    icon: "bar-chart",
    keywords: ["reports", "analytics", "data"],
    when: (c) => c.user.roles.includes("manager") || c.user.roles.includes("admin"),
    action: { kind: "dialog", dialog: "generateReport" },
  },
  {
    id: "system.logout",
    title: "Sign Out",
    subtitle: "Log out of the application",
    section: "Account",
    icon: "log-out",
    keywords: ["logout", "signout", "exit"],
    action: { kind: "server", name: "logout" },
  },
  // Quick navigation based on current context
  {
    id: "nav.assets",
    title: "Assets",
    section: "Quick Nav",
    icon: "package",
    keywords: ["assets"],
    action: { kind: "navigate", href: "/dashboard/assets" },
  },
  {
    id: "nav.work-orders", 
    title: "Work Orders",
    section: "Quick Nav",
    icon: "clipboard",
    keywords: ["work", "orders"],
    action: { kind: "navigate", href: "/dashboard/work-orders" },
  },
]
